version: "3.7"

networks:
  dockerapi-dev:
    driver: bridge
    
services:
  dockerapi:
    image: dockerapi:latest
    depends_on:
      - 'postgres_image'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:80'
      - '5000:5000'
    environment:
      DB_CONNECTION_STRING: 'host=postgres_image;port=5432;database=supermarketdb;username=superuser;password=superpassword;'
    networks: 
      - dockerapi-dev
  
  postgres_image:
    image: postgres:latest
    ports:
      - '5432'
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'superuser'
      POSTGRES_PASSWORD: 'superpassword'
      POSTGRES_DB: 'supermarketdb'
    networks:
      - dockerapi-dev

volumes: 
  db_volume: